name = "vitesse-worktop"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "dist",entry-point = "workers-site"}
compatibility_date = "2022-01-09"
